export const ADD_TEAM="ADD_TEAM"
export const EDIT_TEAM="EDIT_TEAM"
export const DELETE_TEAM="DELETE_TEAM"
export const GET_TEAM="GET_TEAM"
export const ADD_MATCH="ADD_MATCH"
export const EDIT_MATCH="EDIT_MATCH"
export const DELETE_MATCH="DELETE_MATCH"
export const GET_MATCH="GET_MATCH"

export const ADD_PLAYER="ADD_PLAYER"
export const EDIT_PLAYER="EDIT_PLAYER"
export const DELETE_PLAYER="DELETE_PLAYER"
export const GET_PLAYER="GET_PLAYER"

export const ADD_SCORE="ADD_SCORE"
export const EDIT_SCORE="EDIT_SCORE"
export const DELETE_SCORE="DELETE_SCORE"
export const GET_SCORE="GET_SCORE"
export const LOGIN="LOGIN"